### ISSUE TITLE
Full selected text not available for copying

### ISSUE THREAD

**Issue by SpongebobSquamirez** [0xbad1d3a5/Kaku#18]
In normal (non-instant) mode, Kaku used to at least allow you to copy the entire selection of text, by performing OCR on the whole thing, even if it didn't have space to display the full result. I'd like this feature back in some form so that I can copy sentences to create Anki cards.

**Comment by 0xbad1d3a5** [comment]
I pushed v1.3.46 to the beta which should address this issue. Can you test it out @weirdalsuperfan?

**Comment by SpongebobSquamirez** [comment]
Thanks for that! It looks like it works.

Unless you have another use for the bottom corners, it would be nice if they were included in the "sides" used to scroll with. The bottom looks pretty open, but the sides are tight and even with my tiny fingers clicking the sides without accidentally selecting a character is a delicate exercise.
![Screenshot_20190311-210622_Chrome](https://user-images.githubusercontent.com/11866755/54123064-11e10280-4442-11e9-89e2-5826fc4fd234.jpg)

**Comment by 0xbad1d3a5** [comment]
Hmm... not sure why you're having a hard time tapping, from your image the tap area should be roughly the size of the kanji (I'm eyeballing here, but the red should show the trigger area):

![image](https://user-images.githubusercontent.com/878158/54186633-0e14a680-4469-11e9-8de3-a47119f5944f.png)


Including it in the bottom part of the window is a bit difficult, since that's also where the ScrollView is. It looks empty when there's no kanji selected but fills up after the the definition comes in.

**Comment by 0xbad1d3a5** [comment]
Closing issue since feature is now in prod and haven't heard about any complaints. Let me know if trying to touch the edge is still a problem after a while though.
