### ISSUE TITLE
App disappears from home screen on update

### ISSUE THREAD

**Issue by SpongebobSquamirez** [0xbad1d3a5/Kaku#27]
This happens almost every time there's an update, but it only seems to occur with this app. I have to re-add the shortcut to my home screen or whatever every time the app updates. Luckily it leaves a nice gaping hole where it used to be so I don't forget where it was.

**Comment by 0xbad1d3a5** [comment]
Out of curiosity, what version of the app do you have installed right now, despite being in the beta program?

I don't follow the standard beta -> production promotion cycle that the Play Store has (due to needing a simple way to show the beta window), so production releases are usually a fresh build, which means the app version will be higher than the beta track until I upload something there. I wonder if the Play Store forces an update to the highest APK version.

**Comment by SpongebobSquamirez** [comment]
I have v.1.3.61, from the Play Store. I have automatic updates turned on, so I know there's been an update to the Play Store whenever I see that the app has vanished from my screen. I assume it's installing the latest beta version, but maybe not?

**Comment by 0xbad1d3a5** [comment]
o.

Ok yeah it seems like the Play Store always wants to update to the highest version code then, which would be production in this case. The beta version should always have the black window with the WARNING THIS IS A BETA VERSION OF KAKU message appear first. Looks like I'll have to change the way I deploy then.

**Comment by 0xbad1d3a5** [comment]
Addressed by ffe226ef936a9501261d935074158eebdd5a8067
